//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteWS.WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.ServiceDBSoap")]
    public interface ServiceDBSoap {
        
        // CODEGEN: Generating message contract since element name getEmpNameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmpName", ReplyAction="*")]
        TesteWS.WS.getEmpNameResponse getEmpName(TesteWS.WS.getEmpNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmpName", ReplyAction="*")]
        System.Threading.Tasks.Task<TesteWS.WS.getEmpNameResponse> getEmpNameAsync(TesteWS.WS.getEmpNameRequest request);
        
        // CODEGEN: Generating message contract since element name GetDateResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDate", ReplyAction="*")]
        TesteWS.WS.GetDateResponse GetDate(TesteWS.WS.GetDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDate", ReplyAction="*")]
        System.Threading.Tasks.Task<TesteWS.WS.GetDateResponse> GetDateAsync(TesteWS.WS.GetDateRequest request);
        
        // CODEGEN: Generating message contract since element name GetLogsMadeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLogsMade", ReplyAction="*")]
        TesteWS.WS.GetLogsMadeResponse GetLogsMade(TesteWS.WS.GetLogsMadeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLogsMade", ReplyAction="*")]
        System.Threading.Tasks.Task<TesteWS.WS.GetLogsMadeResponse> GetLogsMadeAsync(TesteWS.WS.GetLogsMadeRequest request);
        
        // CODEGEN: Generating message contract since element name GetQualquerCoisaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQualquerCoisa", ReplyAction="*")]
        TesteWS.WS.GetQualquerCoisaResponse GetQualquerCoisa(TesteWS.WS.GetQualquerCoisaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQualquerCoisa", ReplyAction="*")]
        System.Threading.Tasks.Task<TesteWS.WS.GetQualquerCoisaResponse> GetQualquerCoisaAsync(TesteWS.WS.GetQualquerCoisaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEmpNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEmpName", Namespace="http://tempuri.org/", Order=0)]
        public TesteWS.WS.getEmpNameRequestBody Body;
        
        public getEmpNameRequest() {
        }
        
        public getEmpNameRequest(TesteWS.WS.getEmpNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getEmpNameRequestBody {
        
        public getEmpNameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEmpNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEmpNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public TesteWS.WS.getEmpNameResponseBody Body;
        
        public getEmpNameResponse() {
        }
        
        public getEmpNameResponse(TesteWS.WS.getEmpNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEmpNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getEmpNameResult;
        
        public getEmpNameResponseBody() {
        }
        
        public getEmpNameResponseBody(string getEmpNameResult) {
            this.getEmpNameResult = getEmpNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDate", Namespace="http://tempuri.org/", Order=0)]
        public TesteWS.WS.GetDateRequestBody Body;
        
        public GetDateRequest() {
        }
        
        public GetDateRequest(TesteWS.WS.GetDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime dataInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime dataFim;
        
        public GetDateRequestBody() {
        }
        
        public GetDateRequestBody(System.DateTime dataInicio, System.DateTime dataFim) {
            this.dataInicio = dataInicio;
            this.dataFim = dataFim;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public TesteWS.WS.GetDateResponseBody Body;
        
        public GetDateResponse() {
        }
        
        public GetDateResponse(TesteWS.WS.GetDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDateResult;
        
        public GetDateResponseBody() {
        }
        
        public GetDateResponseBody(string GetDateResult) {
            this.GetDateResult = GetDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogsMadeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogsMade", Namespace="http://tempuri.org/", Order=0)]
        public TesteWS.WS.GetLogsMadeRequestBody Body;
        
        public GetLogsMadeRequest() {
        }
        
        public GetLogsMadeRequest(TesteWS.WS.GetLogsMadeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLogsMadeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime dataInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime dataFim;
        
        public GetLogsMadeRequestBody() {
        }
        
        public GetLogsMadeRequestBody(System.DateTime dataInicio, System.DateTime dataFim) {
            this.dataInicio = dataInicio;
            this.dataFim = dataFim;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogsMadeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogsMadeResponse", Namespace="http://tempuri.org/", Order=0)]
        public TesteWS.WS.GetLogsMadeResponseBody Body;
        
        public GetLogsMadeResponse() {
        }
        
        public GetLogsMadeResponse(TesteWS.WS.GetLogsMadeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLogsMadeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLogsMadeResult;
        
        public GetLogsMadeResponseBody() {
        }
        
        public GetLogsMadeResponseBody(string GetLogsMadeResult) {
            this.GetLogsMadeResult = GetLogsMadeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQualquerCoisaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQualquerCoisa", Namespace="http://tempuri.org/", Order=0)]
        public TesteWS.WS.GetQualquerCoisaRequestBody Body;
        
        public GetQualquerCoisaRequest() {
        }
        
        public GetQualquerCoisaRequest(TesteWS.WS.GetQualquerCoisaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetQualquerCoisaRequestBody {
        
        public GetQualquerCoisaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQualquerCoisaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQualquerCoisaResponse", Namespace="http://tempuri.org/", Order=0)]
        public TesteWS.WS.GetQualquerCoisaResponseBody Body;
        
        public GetQualquerCoisaResponse() {
        }
        
        public GetQualquerCoisaResponse(TesteWS.WS.GetQualquerCoisaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQualquerCoisaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetQualquerCoisaResult;
        
        public GetQualquerCoisaResponseBody() {
        }
        
        public GetQualquerCoisaResponseBody(string GetQualquerCoisaResult) {
            this.GetQualquerCoisaResult = GetQualquerCoisaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceDBSoapChannel : TesteWS.WS.ServiceDBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDBSoapClient : System.ServiceModel.ClientBase<TesteWS.WS.ServiceDBSoap>, TesteWS.WS.ServiceDBSoap {
        
        public ServiceDBSoapClient() {
        }
        
        public ServiceDBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TesteWS.WS.getEmpNameResponse TesteWS.WS.ServiceDBSoap.getEmpName(TesteWS.WS.getEmpNameRequest request) {
            return base.Channel.getEmpName(request);
        }
        
        public string getEmpName() {
            TesteWS.WS.getEmpNameRequest inValue = new TesteWS.WS.getEmpNameRequest();
            inValue.Body = new TesteWS.WS.getEmpNameRequestBody();
            TesteWS.WS.getEmpNameResponse retVal = ((TesteWS.WS.ServiceDBSoap)(this)).getEmpName(inValue);
            return retVal.Body.getEmpNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TesteWS.WS.getEmpNameResponse> TesteWS.WS.ServiceDBSoap.getEmpNameAsync(TesteWS.WS.getEmpNameRequest request) {
            return base.Channel.getEmpNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<TesteWS.WS.getEmpNameResponse> getEmpNameAsync() {
            TesteWS.WS.getEmpNameRequest inValue = new TesteWS.WS.getEmpNameRequest();
            inValue.Body = new TesteWS.WS.getEmpNameRequestBody();
            return ((TesteWS.WS.ServiceDBSoap)(this)).getEmpNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TesteWS.WS.GetDateResponse TesteWS.WS.ServiceDBSoap.GetDate(TesteWS.WS.GetDateRequest request) {
            return base.Channel.GetDate(request);
        }
        
        public string GetDate(System.DateTime dataInicio, System.DateTime dataFim) {
            TesteWS.WS.GetDateRequest inValue = new TesteWS.WS.GetDateRequest();
            inValue.Body = new TesteWS.WS.GetDateRequestBody();
            inValue.Body.dataInicio = dataInicio;
            inValue.Body.dataFim = dataFim;
            TesteWS.WS.GetDateResponse retVal = ((TesteWS.WS.ServiceDBSoap)(this)).GetDate(inValue);
            return retVal.Body.GetDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TesteWS.WS.GetDateResponse> TesteWS.WS.ServiceDBSoap.GetDateAsync(TesteWS.WS.GetDateRequest request) {
            return base.Channel.GetDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<TesteWS.WS.GetDateResponse> GetDateAsync(System.DateTime dataInicio, System.DateTime dataFim) {
            TesteWS.WS.GetDateRequest inValue = new TesteWS.WS.GetDateRequest();
            inValue.Body = new TesteWS.WS.GetDateRequestBody();
            inValue.Body.dataInicio = dataInicio;
            inValue.Body.dataFim = dataFim;
            return ((TesteWS.WS.ServiceDBSoap)(this)).GetDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TesteWS.WS.GetLogsMadeResponse TesteWS.WS.ServiceDBSoap.GetLogsMade(TesteWS.WS.GetLogsMadeRequest request) {
            return base.Channel.GetLogsMade(request);
        }
        
        public string GetLogsMade(System.DateTime dataInicio, System.DateTime dataFim) {
            TesteWS.WS.GetLogsMadeRequest inValue = new TesteWS.WS.GetLogsMadeRequest();
            inValue.Body = new TesteWS.WS.GetLogsMadeRequestBody();
            inValue.Body.dataInicio = dataInicio;
            inValue.Body.dataFim = dataFim;
            TesteWS.WS.GetLogsMadeResponse retVal = ((TesteWS.WS.ServiceDBSoap)(this)).GetLogsMade(inValue);
            return retVal.Body.GetLogsMadeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TesteWS.WS.GetLogsMadeResponse> TesteWS.WS.ServiceDBSoap.GetLogsMadeAsync(TesteWS.WS.GetLogsMadeRequest request) {
            return base.Channel.GetLogsMadeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TesteWS.WS.GetLogsMadeResponse> GetLogsMadeAsync(System.DateTime dataInicio, System.DateTime dataFim) {
            TesteWS.WS.GetLogsMadeRequest inValue = new TesteWS.WS.GetLogsMadeRequest();
            inValue.Body = new TesteWS.WS.GetLogsMadeRequestBody();
            inValue.Body.dataInicio = dataInicio;
            inValue.Body.dataFim = dataFim;
            return ((TesteWS.WS.ServiceDBSoap)(this)).GetLogsMadeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TesteWS.WS.GetQualquerCoisaResponse TesteWS.WS.ServiceDBSoap.GetQualquerCoisa(TesteWS.WS.GetQualquerCoisaRequest request) {
            return base.Channel.GetQualquerCoisa(request);
        }
        
        public string GetQualquerCoisa() {
            TesteWS.WS.GetQualquerCoisaRequest inValue = new TesteWS.WS.GetQualquerCoisaRequest();
            inValue.Body = new TesteWS.WS.GetQualquerCoisaRequestBody();
            TesteWS.WS.GetQualquerCoisaResponse retVal = ((TesteWS.WS.ServiceDBSoap)(this)).GetQualquerCoisa(inValue);
            return retVal.Body.GetQualquerCoisaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TesteWS.WS.GetQualquerCoisaResponse> TesteWS.WS.ServiceDBSoap.GetQualquerCoisaAsync(TesteWS.WS.GetQualquerCoisaRequest request) {
            return base.Channel.GetQualquerCoisaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TesteWS.WS.GetQualquerCoisaResponse> GetQualquerCoisaAsync() {
            TesteWS.WS.GetQualquerCoisaRequest inValue = new TesteWS.WS.GetQualquerCoisaRequest();
            inValue.Body = new TesteWS.WS.GetQualquerCoisaRequestBody();
            return ((TesteWS.WS.ServiceDBSoap)(this)).GetQualquerCoisaAsync(inValue);
        }
    }
}
